### ISSUE TITLE
Advanced module 

### ISSUE THREAD

**Issue by huglester** [anomalylabs/example-module#1]
Hello,

I think example module should be more of advanced module, like relations, different field type (if not all), so people could look at it and get the basic idea on how all works... so they just 'remove some fields from config', rename to 'AwesomeMOdule' and they are ready to go...

Deleting is always easier than adding :D

**Comment by RyanThompson** [comment]
Ya I am going to start simple. There are plenty of other modules that will be more advanced / better practice to show. This will be strictly a foot in the door type approach. Not even doc blocking it.

Check out for a (slightly) more advanced example: https://github.com/anomalylabs/redirects-module

Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581
